// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-bJwWAYeiRjSKPM_0TqrlooKVuvwWYY0',
    appId: '1:718949512727:web:cfad2e490ef31858a84e52',
    messagingSenderId: '718949512727',
    projectId: 'pandora32-6f15b',
    authDomain: 'pandora32-6f15b.firebaseapp.com',
    databaseURL: 'https://pandora32-6f15b-default-rtdb.firebaseio.com',
    storageBucket: 'pandora32-6f15b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPhQ51r-gzddt9iJs8tNxirSUpYhX75I',
    appId: '1:718949512727:android:ae937d7c2325d370a84e52',
    messagingSenderId: '718949512727',
    projectId: 'pandora32-6f15b',
    databaseURL: 'https://pandora32-6f15b-default-rtdb.firebaseio.com',
    storageBucket: 'pandora32-6f15b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZbru75byTLg7Z_1Q8_E7VMKHESvCr-m0',
    appId: '1:718949512727:ios:b21d429770ce3e32a84e52',
    messagingSenderId: '718949512727',
    projectId: 'pandora32-6f15b',
    databaseURL: 'https://pandora32-6f15b-default-rtdb.firebaseio.com',
    storageBucket: 'pandora32-6f15b.firebasestorage.app',
    iosBundleId: 'com.example.pandora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZbru75byTLg7Z_1Q8_E7VMKHESvCr-m0',
    appId: '1:718949512727:ios:b21d429770ce3e32a84e52',
    messagingSenderId: '718949512727',
    projectId: 'pandora32-6f15b',
    databaseURL: 'https://pandora32-6f15b-default-rtdb.firebaseio.com',
    storageBucket: 'pandora32-6f15b.firebasestorage.app',
    iosBundleId: 'com.example.pandora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-bJwWAYeiRjSKPM_0TqrlooKVuvwWYY0',
    appId: '1:718949512727:web:ad52fbeacdf08618a84e52',
    messagingSenderId: '718949512727',
    projectId: 'pandora32-6f15b',
    authDomain: 'pandora32-6f15b.firebaseapp.com',
    databaseURL: 'https://pandora32-6f15b-default-rtdb.firebaseio.com',
    storageBucket: 'pandora32-6f15b.firebasestorage.app',
  );
}
